import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import commonStyles from "../../styles/Home.module.css";
import styles from "./Login.module.css";
import "antd/dist/antd.css";
import Form, { Item, useForm } from "../../components/Form";
import { Button, Checkbox, Input } from "antd";
import { LoginRequestDef } from "../../types/auth.types";
import { useState } from "react";
import useAuth from "../../hooks/useAuth";
import { PASSWORD } from "../../constants/validate.regex";

const Home: NextPage = () => {
  const [form] = useForm<LoginRequestDef>();
  const [loading, setLoading] = useState<boolean>(false);
  const { login } = useAuth();

  const handleSubmit = async (data: LoginRequestDef) => {
    setLoading(true);
    await login(data.email, data.password);
    setLoading(false);
  };

  return (
    <div className={commonStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h2 className={styles.title}>Title</h2>
      </header>
      <main className={commonStyles.main}>
        <Form form={form} onFinish={handleSubmit} className={styles.loginWrap}>
          <Item
            name="email"
            label="Email"
            form={form}
            rules={[{ type: "email" }, { required: true }]}
          >
            <Input />
          </Item>
          <Item
          label="Password"
          name="password"
          rules={[{ required: true }, PASSWORD]}
          form={form}
        >
          <Input.Password />
        </Item>
        <Item
          className={commonStyles.checkbox}
          name="isRemember"
          valuePropName="checked"
          form={form}
        >
          <Checkbox>Save Password</Checkbox>
        </Item>
          <Item shouldUpdate noStyle form={form}>
            {({ isFieldsTouched, getFieldsError }) => (
              <Button
                className={commonStyles.submitButton}
                type="primary"
                htmlType="submit"
                disabled={
                  !isFieldsTouched() ||
                  !!getFieldsError().filter(({ errors }) => errors.length)
                    .length
                }
                loading={loading}
              >
                Submit
              </Button>
            )}
          </Item>
        </Form>
        {/* <div className={style.loginWrap}>
          <h2 className={style.subTitle}>Login</h2>
          <p className={style.label}>Username</p>
          <input className={style.input} type="text" />
          <p className={style.label}>Password</p>
          <div className={style.inpPasswordWrap}>
            <input className={style.input} type="text" />
            <EyeInvisibleOutlined className={style.iconEye}/>
          </div>
        </div> */}
      </main>

      <footer className={commonStyles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={commonStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
