import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import Link from "next/link";
import DefaultLayout from "../components/layouts/DefaultLayout";

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h2 className={styles.title}>Start next app</h2>

          <p className={styles.description}>
            <Link href="/productss" passHref>
              <a>See list product</a>
            </Link>
            <br />
            <Link href="/users" passHref>
              <a>See list user</a>
            </Link>
          </p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </DefaultLayout>
  );
};

export default Home;
